# This is a basic workflow to help you get started with Actions

name: Issues Opened Workflow

# Run workflow when a new issue is opened
on:
  issues:
     types:
       - opened
       - edited

jobs:
  check_issue_creator_status:
    runs-on: ubuntu-latest
    name: A job to check status of issue creator
    steps:
    - name: Print the GitHub event
      run: echo "$GITHUB_CONTEXT"
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}

    - name: Check if user is not a member
      if: ${{ github.event.issue.author_association == 'NONE' }}
      run: |
        echo "Issue was created by a non-member."

    - name: Check if user is a contributor or member
      if: ${{ github.event.issue.author_association == 'CONTRIBUTOR' || github.event.issue.author_association == 'MEMBER' }}
      run: |
        echo "Issue was created by a member."
